#+TITLE: Random Encounters for Skullport
# Taken from

    A cockatrice races down the street, jumping over people and biting them as it rushes in the way of the PCs.

    A human bard with an eyepatch watches two trolls as they crush the supporting pillars of a house that comes crashing down on them after a few minutes. The trolls get out of the rubble with a crashed body in hand.

    A fight breaks out between two hardy looking barbarians. A skull of Skullport flies in to the scene and swiftly desintegrates one and turns the other into a fish that suffocates quickly.

    A bald, tattooed, armored figure interrogates a young apprentice of some sort in a leather appron while two wizards of Thay watch what he has to say. They inquire info about his master Dwarnid Inkpeddler.

    There's a flash of blinding light, the stech of a nausiating aroma and someone tries to steal something of from a PC. When the PCs regain their sight they only see the item floating away in the crowd, carried by and invisible being.

    Ahmaergo, the Horned Dwarf, right hand of the Xanathar hurries by angrily with a few mean looking fellows by his side. He carries the still blood dripping chopped of head of a human.

    A group of six yuan-ti slavers herd several dozen slaves of various races on chains. The PCs see two children aged about ten amongst the slaves.

    A large shipment of alchohol is carried on carts by several humans armed to the teeth. They have quite a few people following them unobtrusively.

    A human in fine cloths and a jet black long hair collapses gasping for air and dies in a couple of seconds. Some folks jump on his belongings in an instant and then life goes on as usual.

    A swarm of giant rats pour out from an ally and attack everyone on the street.

    Six pickpockets jump on a PC from nowhere and take what they can then run off.

    A cultist of Cyric has been following the PCs and now contacts them in relation to a previous encounter or deal they had and provides misleading information to cause discord.

    A skulker gang of orgres led by a half-ogre cleric of Loviatar tries to enslave the PCs.

    The Street Scrapers, trash removals of Skullport, pile up a massive amount of trash at the main entrance of a shop that did not pay their ransom fee. The owner threatens them verbally from the inside but is affraid to confront them any other way.

    Several pieces of cloth and trash start whirling in the air in front of the PCs and the Rag Mage appears. He eyes them for a moment then casts fear on them and vanishes.

    The PCs spot Grimmbold the Gith, the githzerai agent of the Zentharim in Skullport, at a secret meeting with some priests of Bane. This information could be sold to other factions in the city.

    An otyugh crashes a sewer gate near the PCs and starts devouring anything it sees be it food, trash or a creature it sees.

    An earthquake shakes the streets and debris falls from above on the PCs and all bystanders.

    A few orc slaves rampage on the streets waving stolen weapons and attacking everyone in their way. In a few moments a couple of Iron Ring slavers stop them.

    Two gargoyles from the Tower of Seven Woes, slaver stronghold of Loviatar, try to grab a PC and carry him or her away.

    One of Spider's Fleet o' Feer courriers is chased by a yuan-ti slaver. The courrier, a human rogue, hides behind the PCs for protection. He delivers a message to a Xanathar guild member.

    A street vendor sells cheap trinkets on a "you touch it, you bought it" basis which is written on a small unreadable board. A PC examining the wares is immediately asked for its price by the owner, waving a fake wand of lightning bolt.

    A female tiefling fake seer "divines" the future of bystanders for free. A group of low-life sailors and laborers watch him while other tieflings rob them and the PCs if they start watching. The crowd quickly realises the thefts and accuses the PCs.

    Zombie laborers change the street cobbles in front of the PCs. One of them is an old acquaintance of a PC.

    A shipment of Misker, the Pirate Tyrant smuggler beholder, is stuck due to a broken wheel of the cart. The stressed thugs have to deliver it on time to the docks and they ask the PCs for help.

    A lost young noble of Waterdeep in torn clothes, looking more like a beggar, stumbles past, murmuring something about “finding the golden peacock”.

    A Xanathar slaver drags along three sobbing female halflings on a chain and asks for directions.

    A skull of Skullport flyies by with great speed, bounces of a corner and flyes away.

    A couple of "Mhaug Hogs", zombies with twisted necks made by Mhaug the hag, bound by long chain try to move along the street. They attack if disturbed in their struggle.

    Someone empties a night pot to the street from an opening on a higher level or a window.

    A dwarven beggar covered with oozing ulcers is begging for some food or some coins.

    Lady Mirage, a feared illusionist performer of The Troll's Guffaw theater passes by. People shy away from her path and people whisper remarks about her latest deadly performance.

    A dozen drunken sailors from Chult are loudly commenting things they see on the streets. A single mind flayer follows them from a distance.

    Ten slaves, commanded by a sad Calashite merchant, pull a heavy cart with the very lifelike statue of a hill giant dressed as a noble on it.

    A drow noble of House Tanor'Thal argues with a silk merchant from top of her giant spider mount, surrounded by her four drow guards.

    A couple of slaves, guarded by four thugs push a cart packed with a heap of bones of different origin and size, all neatly whitened and polished. The PCs can spot a ring on a skeletal hand.

    A crazed imp tries to steal something from the PCs. If caught it starts yelling and calls the skulls of Skullport very loudly, making a big scene. There's a chance a skull of Skullport appears.

    A larger disjoined stalactite falls from the ceiling.

    Pirates of Misker the Pirate Tyrant beholder, with an eye tattooed to each of their foreheads walk by in a hurry. One of them pushes a PC out of the way to make way for their group.

    An enraged wizards in purple robes throws a fireball at an unsuspecting rival wizard in the open streets. Many die in the assault and soon the offenders head is separated from his body.

    Two cloacked male figures pass by. One of the PCs accidentally touches one of them they can see through his illusiory disguise revealing a scar face male drow wearing a violet eyemask.

    An old obese gnome in rags offers to shine weapons or boots. If they allow him he tells about a few notable places in the city.

    A duergar merchant confronts the PCs and wants to buy an expensive looking armor or weapon off of them. He and his duergar guards keep following them if they don't sell him what he desires.

    Four bugbears pick on the PCs. They say the PCs murdered their slaves, they demand compensation and boast that they are high ranking Xanathar guild members.

    A human slave from Waterdeep has escaped and wants the PCs to help him leave Skullport as soon as possible. He has no valuables.

    Two beautiful elven girls are on sale at a nearby slave auction and the price is getting staggeringly high. The girl weeps and a crowd gathers to see what the final price will be.

    The mutilated corpse of a half-orc crashes to the street from a great height.

    Some undead stirges fly into the crowd looking for dinner. A few minutes later a troubled looking wizard runs to the spot, then quickly leaves after seeing what happened.

    The PCs look into a narrow alley and see two ghouls that look like children eating a larger corpse.

    Slaves pull a cart packed with sickly looking fish. As they come closer the PCs can spot a halfling hiding under the foul smelling pile.
